In [7]:
import numpy as np

# 주요 기능 및 예제

# 배열 생성 (np.array())
# 1차원 배열 생성
arr1 = np.array([1,2,3,4,5])

print(f'arr1 : {arr1}')

# 2차원 배열 생성
arr2 = np.array([
    [1,2,3]
    ,[4,5,6]
])
print(f'arr2 : {arr2}')

# 3차원 배열 생성

arr3 =np.array(
    [
        [
            [1,2]
            ,[3,4]
            ,[5,6]
            ,[7,8]
        ]
    ]
)
print(f'arr3 : {arr3}')

arr1 : [1 2 3 4 5]
arr2 : [[1 2 3]
 [4 5 6]]
arr3 : [[[1 2]
  [3 4]
  [5 6]
  [7 8]]]


In [ ]:
import numpy as np

# 주요 기능 및 예제

# 배열 생성 (np.array())
# 1차원 배열 생성
arr1 = np.array([1,2,3,4,5])

# 2차원 배열 생성
arr2 = np.array([
    [1,2,3]
    ,[4,5,6]
])


# 3차원 배열 생성

arr3 =np.array(
    [
        [
            [1,2]
            ,[3,4]
            ,[5,6]
            ,[7,8]
        ]
    ]
)
print('='*50)

print(f'arr1 배열의 차원 : {arr1.ndim}')
print(f'arr2 배열의 차원 : {arr2.ndim}')
print(f'arr3 배열의 차원 : {arr3.ndim}')
print('='*50)
print(f'arr1 배열의 크기 : {arr1.shape}')
print(f'arr2 배열의 크기 : {arr2.shape}')
print(f'arr3 배열의 크기 : {arr3.shape}')

print('='*50)

print(f'arr1 배열의 원소 개수 : {arr1.size}')
print(f'arr2 배열의 원소 개수 : {arr2.size}')
print(f'arr3 배열의 원소 개수 : {arr3.size}')

print('='*50)

print(f'arr1 배열의 데이터 타입 : {arr1.dtype}')
print(f'arr2 배열의 데이터 타입 : {arr2.dtype}')
print(f'arr3 배열의 데이터 타입 : {arr3.dtype}') # ndarray는 동일타입만 저장 할 수 있다

arr1 배열의 차원 : 1
arr2 배열의 차원 : 2
arr3 배열의 차원 : 3
arr1 배열의 크기 : (5,)
arr2 배열의 크기 : (2, 3)
arr3 배열의 크기 : (1, 4, 2)
arr1 배열의 원소 개수 : 5
arr2 배열의 원소 개수 : 6
arr3 배열의 원소 개수 : 8
arr1 배열의 데이터 타입 : int32
arr2 배열의 데이터 타입 : int32
arr3 배열의 데이터 타입 : int32


In [ ]:
import numpy as np
# 특정값을 갖는 배열 생성
# 0값을 갖는 배열 : np.zeros((행,열))
zeroes_ =np.zeros(
    (3,3)
)
print(zeroes_)
print('='*50)
# 1값을 갖는 배열 : np.ones((행,열))
ones_ =np.ones(
    (3,3)
)
print(ones_)
print('='*50)
# 특정값으로 채운 배열 : np.full((행,열),특정값)

full=np.full((2,2),5)
print(full)

print('='*50)
# 연속된 숫자로 채운 배열 생성 : np.arange(start,end, stop)
arr4=np.arange(1,10,2)
print(arr4)
print('='*50)

# np.linspace(start,end,count)
lin_arr=np.linspace(0,100,5) # 0~100 사이에서 5개 값으로 생성
print(lin_arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[5 5]
 [5 5]]
[1 3 5 7 9]
[  0.  25.  50.  75. 100.]


In [27]:
import numpy as np

# 난수 배열 생성

# numpy의 random모듈을 사용하면 다양한 난수 배열을 생성 할 수 있다.

# np.random.rand(행,열) : 0~1사이의 난수를 가진 배열 생성
np.random.seed(42) # seed에 의해 rand 값이 바뀔수도 있고 안 바뀔수도 있다

rand_arr = np.random.rand(2,3)
print(rand_arr)

# 정규분포를 따르는 난수 배열 생성 : np.random.randn(행,열)
randn_arr=np.random.randn(2,2)
print(randn_arr)

# 특정 범위의 정수 난수 배열 생성 : np.random.randint(start,ent,[(행,열)])
randint_arr= np.random.randint(1,10,[3,4])
print(randint_arr)

[[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]]
[[ 1.57921282  0.76743473]
 [-0.46947439  0.54256004]]
[[5 1 6 9]
 [1 3 7 4]
 [9 3 5 3]]


In [30]:
import numpy as np

# 배열 연산(더하기, 빼기, 곱셈, 나눗셈, 제곱)
a_vector =np.array([1,2,3])
b_vector =np.array([4,5,6])
print(f'덧셈 : {a_vector+b_vector}')
print(f'뺄셈 : {a_vector-b_vector}')
print(f'곱셈 : {a_vector*b_vector}')
print(f'제곱 : {a_vector**b_vector}')

덧셈 : [5 7 9]
뺄셈 : [-3 -3 -3]
곱셈 : [ 4 10 18]
제곱 : [  1  32 729]


In [41]:
import numpy as np

# 배열 인덱싱 및 슬라이싱
arr=np.array([
    [1,2,3]
    ,[4,5,6]
    ,[7,8,9]
])

print(f'arr : {arr}')
print(f'첫번째 행, 두번째 열 : {arr[0][1]}') # arr[행][열]
print(f'첫번째 행, 두번째 열 : {arr[0,1]}') # arr[행,열]

# 특정 행 슬라이싱
print(f'첫번째 행 : {arr[0]}')
print(f'첫번째 행 : {arr[0,]}')
print(f'첫번째 행 : {arr[0,:]}')

# 특정 열 슬라이싱
print(f'두번째 열 : {arr[:,1]}')

# 부분 배열 가져오기
print(f'2x2 부분 배열 : {arr[1:3,1:3]}')

arr : [[1 2 3]
 [4 5 6]
 [7 8 9]]
첫번째 행, 두번째 열 : 2
첫번째 행, 두번째 열 : 2
첫번째 행 : [1 2 3]
첫번째 행 : [1 2 3]
첫번째 행 : [1 2 3]
두번째 열 : [2 5 8]
2x2 부분 배열 : [[5 6]
 [8 9]]


In [43]:
import numpy as np

# 선형대수 연산
# 선형 변환(Linear Transformation)은 벡터나 행렬을 다른 벡터나 행렬로 변환하는 수학적 과정
# 특정 방향으로 확장/축소하는 역할
A = np.array([
    [1,2]
    ,[3,4]
])
B = np.array([
    [1,1]
    ,[2,2]
])

# 점 곱 
# 주어진 데이터(A)를 가중치(B)로 선형 변환한 것이다.
dot_prod=np.dot(A,B)
print(f'행 열 곱 : {dot_prod}')

행 열 곱 : [[ 5  5]
 [11 11]]


In [45]:
import numpy as np

# 전체 행렬 : transpose
A = np.array([
    [1,2]
    ,[3,4]
])
B = np.array([
    [1,1]
    ,[2,2]
])

A,A.T,A.transpose()

(array([[1, 2],
        [3, 4]]),
 array([[1, 3],
        [2, 4]]),
 array([[1, 3],
        [2, 4]]))

In [49]:
import numpy as np

a=np.array([1,2,3])
print(f'a shape : {a.shape}')
b=np.array([1,2,3])
print(f'b shape : {b.shape}')
print(np.dot(a,b))
print(np.dot(a.T,b))

a shape : (3,)
b shape : (3,)
14
14


In [52]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])
print(f'a shape : {a.shape}')

b = np.array([1, 2, 3])
print(f'b shape : {b.shape}')

print(np.dot(a, b))

try:
    print(np.dot(a.T, b))
except Exception as e:
    print('오류: ' + str(e))


a shape : (2, 3)
b shape : (3,)
[14 32]
오류: shapes (3,2) and (3,) not aligned: 2 (dim 1) != 3 (dim 0)


In [ ]:
import numpy as np

# 역행렬
# 역행렬 존재하는 조건
# 1. 정사각 행렬(Square Matrix) (nxn)
# 2. 행렬식이 0이 아니어야한다. 행렬식이 0 이면 역행렬이 존재하지 않고 이러한 행렬을 특이행렬(Singular Matrix)라고 한다.
#    AxA-1 = A-1
#    단위 행렬(Identity Matrix), 행렬 곱셈의 항등원 역할



# 행렬식 : 정사각 행렬의 스칼라(단일값) 값을 의미한다.
# 특정 행렬(데이터)이 선형변환에서 공간을 얼마나 변환시키는지를 나타나는 값

# 행렬식이 0이면 해당 행렬이 역행렬을 가질 수 없다(det(A)=0)
# 해당 행렬이 선형 종속(Linear Dependent)이 된다

# 행렬식이 0이 아니면
# 행렬이 가역(invertible)하며, 역행렬이 존재한다.

# 역행렬과 행렬식 계산
# 1. 역행렬 구하기(np.linalg.inv())

# 행렬 A : 2X2 정사각행렬
A = np.array([
    [4,7]
    ,[2,6]
]
)

# 역행렬 구하기
A_inv = np.linalg.inv(A)

print(A_inv)



[[ 0.6 -0.7]
 [-0.2  0.4]]


In [ ]:
import numpy as np

# 역행렬
# 역행렬 존재하는 조건
# 1. 정사각 행렬(Square Matrix) (nxn)
# 2. 행렬식이 0이 아니어야한다. 행렬식이 0 이면 역행렬이 존재하지 않고 이러한 행렬을 특이행렬(Singular Matrix)라고 한다.
#    AxA-1 = A-1
#    단위 행렬(Identity Matrix), 행렬 곱셈의 항등원 역할



# 행렬식 : 정사각 행렬의 스칼라(단일값) 값을 의미한다.
# 특정 행렬(데이터)이 선형변환에서 공간을 얼마나 변환시키는지를 나타나는 값

# 행렬식이 0이면 해당 행렬이 역행렬을 가질 수 없다(det(A)=0)
# 해당 행렬이 선형 종속(Linear Dependent)이 된다

# 행렬식이 0이 아니면
# 행렬이 가역(invertible)하며, 역행렬이 존재한다.

# 역행렬과 행렬식 계산
# 1. 역행렬 구하기(np.linalg.inv())

# 행렬 A : 2X2 정사각행렬
A = np.array([
    [4,7]
    ,[2,6]
]
)

B = np.array([
    [4,12]
    ,[2,6]
]
)


# 역행렬 구하기
A_inv = np.linalg.inv(A)
B_inv = np.linalg.inv(B)

print(A_inv)
print(B_inv)

# 단위 행렬 구하기
A_I = np.dot(A,A_inv)
print(A_I)

B_I = np.dot(B,B_inv)
print(B_I)


LinAlgError: Singular matrix

In [12]:
import numpy as np

# 행렬식 구하기 (np.linalg.det())

# 3x3 정사각 행렬
B = np.array(
    [
        [1,2,3]
        ,[4,5,6]
        ,[7,8,9]
    ]
)
print(B)

# 역행렬 구하기
B_inv = np.linalg.inv(B)
print(B_inv)

# 행렬식 구하기
B_det = np.linalg.det(B)

print(B_det)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[-4.50359963e+15  9.00719925e+15 -4.50359963e+15]
 [ 9.00719925e+15 -1.80143985e+16  9.00719925e+15]
 [-4.50359963e+15  9.00719925e+15 -4.50359963e+15]]
6.66133814775094e-16


In [13]:
import numpy as np

# 행렬식 구하기 (np.linalg.det())

# 3x3 정사각 행렬
B = np.array(
    [
        [1,2,3]
        ,[4,5,6]
        ,[7,8,10]
    ]
)
print(B)

# 역행렬 구하기
B_inv = np.linalg.inv(B)
print(B_inv)

# 행렬식 구하기
B_det = np.linalg.det(B)

print(B_det)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8 10]]
[[-0.66666667 -1.33333333  1.        ]
 [-0.66666667  3.66666667 -2.        ]
 [ 1.         -2.          1.        ]]
-2.9999999999999982


In [16]:
import numpy as np

# 특이 행렬(Singular Matrix)

C = np.array(
    [
        [1,2]
        ,[2,4]
    ]
)

print(C)

# 행렬식 확인
print(f'행렬식 값 : {np.linalg.det(C)}')

try:
    c_inv = np.linalg.inv(C)
    print(f'역행렬 : {c_inv}')
except np.linalg.LinAlgError:
    print('역행렬을 가질 수 없는 특이 행렬이다.')
    

[[1 2]
 [2 4]]
행렬식 값 : 0.0
역행렬을 가질 수 없는 특이 행렬이다.


# 역행렬의 해석과 의미

1. 역행렬의 존재 조건
- 행렬  A가 정사각 행렬이어야 한다.
- 행렬식이 0이 아니어야한다.
- 선행독립(Linear Independent)인 열벡터를 가져야 한다.
    - 즉, 행렬의 열벡터들이 서로 독립적이면 역행렬이 존재하게 된다.

2. 해석
2.1 선형변환 관점
- 행렬 A는 공간을 변형시키는 선형 변환으로 볼 수 있다.
- 역행렬은 이 변환을 되돌리는 역할을 한다.(공간을 복원하는 역할)

2.2 기하학적 관점
- 역행렬이 존재 : 변환이 가역적이라면, 좌표 공간을 다시 원래대로 복원
- 역행렬이 존재 x : 변환이 공간을 축소시키거나, 특정 차원으로 줄여 되둘리 수 없는 변환(Singular Transformation)이 된다.

### Singular Tranformation
#### 역행렬이 존재하지 않는 경우는 공간을 완전히 축소시키는 변환을 의미한다.